version: '3.9'
services:
  readme.blog.postgres:
    image: postgres:14-alpine
    container_name: readme.blog.postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

    ports:
      -  ${POSTGRES_PORT}:5432

    volumes:
      - readme.postgres.blog:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - readme.blog

  readme.blog.pgadmin:
    image: dpage/pgadmin4
    container_name: readme.blog.pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"

    ports:
      - 8082:80

    depends_on:
      - readme.blog.postgres

    networks:
      - readme.blog

  readme.blog.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.blog.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

    ports:
      - ${MONGODB_PORT}:27017

    volumes:
      - readme.mongo.blog:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGODB_DATABASE} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.blog.mongo.ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: readme.blog.mongo.ui

    ports:
      - 8083:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@readme.blog.mongo:27017/

volumes:
  readme.postgres.blog:
  readme.mongo.blog:

networks:
  readme.blog:
      driver: bridge
